// components/Header.tsx
import { Link } from "react-router-dom";
import "../styles/Home.css";

type Action = {
  label: string;
  url: string;
}

type HeaderProps = {
  name?: string;
  avatar?: { url?: string; alt?: string };
  actions?: Action[];
}

const Header: React.FC<HeaderProps> = ({ name, avatar, actions = [] }) => {
    const isInternal = (url: string) => url.startsWith("/");
    return (
      <header className="siteHeader">
        <div className="wrap">
          <div className="navRow">
            <a href="/" className="brand" aria-label="home">
              <div className="brandLogo">
                {avatar?.url
                  ? <img className="brandPhoto" src={avatar.url} alt={avatar?.alt ?? "brand photo"} width={36} height={36}/>
                  : <div className="brandPhoto" aria-hidden="true" />
                }
              </div>
              <span className="brandName">{name}</span>
            </a>

            {actions.length > 0 && (
            <nav aria-label="Actions" className="navLinks">
              {actions.map((act, i) => 
                isInternal(act.url) ? (
                  <Link key={`${act.url}-${i}`} to={act.url} className="navLink">
                    {act.label}
                  </Link>
                ) : (
                  <a key={`${act.url}-${i}`} href={act.url} className="navLink">
                    {act.label}
                  </a>
                )
              )}
            </nav>
          )}
          </div>
        </div>
      </header>
    );
}

export default Header;

// src/components/Header.svelte
  <script lang="ts">
    import "../styles/Home.css";

    const name = "Jeffrey Hoelzel Jr.";
    const avatar = {
      url: import.meta.env.BASE_URL + "headshot_2025_Jeffrey-Hoelzel_3.jpg", 
      alt: "Headshot of Jeffrey Hoelzel Jr."
    };

  const actions = [
    {
      label: "View projects", 
      url: "#/projects"
    }, 
    {
      label: "Contact me", 
      url: "#/contact"
    }, 
    {
      label: "View resume", 
      url: "#/resume"
    }
  ];
  </script>
  
  <!-- Header -->
  <header class="siteHeader">
    <div class="wrap">
      <div class="navRow">
        <a href="#/" class="brand" aria-label="home">
          <div class="brandLogo">
            {#if avatar.url}
              <img
                class="brandPhoto"
                src={avatar.url}
                alt={avatar.alt}
                width="36"
                height="36"
              />
            {:else}
              <div class="brandPhoto" aria-hidden="true"></div>
            {/if}
          </div>
          <span class="brandName">{name}</span>
        </a>

        {#if actions.length}
          <nav aria-label="Actions" class="navLinks">
            {#each actions as action}
              <a href={action.url} class="navLink">
                {action.label}
              </a>
            {/each}
          </nav>
        {/if}
      </div>
    </div>
  </header>
