// client/src/App.tsx
import { Routes, Route } from "react-router-dom";
import Home from "./components/Home"
import Projects from "./components/Projects";

const App: React.FC = () => {
  return (
    <main style={{ fontFamily: "system-ui", padding: "2rem" }}>
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="/projects" element={<Projects />} />
      </Routes>
    </main>
  );
}

export default App;

// src/App.svelte
<script lang="ts">
  import Router from "svelte-spa-router";

  import Header from "./components/Header.svelte";
  import Footer from "./components/Footer.svelte";

  import Home from "./pages/Home.svelte";
  import Projects from "./pages/Projects.svelte";
  import Resume from "./pages/Resume.svelte";
  import ComingSoon from "./pages/ComingSoon.svelte";

  const routes = {
    "/": Home,
    "/projects": Projects,
    "/resume": Resume,
    "*": ComingSoon,
  };
</script>

<Header />
<main>
  <Router {routes} />
</main>
<Footer />
